### PR TITLE
add Dockerfile

### PR DESCRIPTION
**Pull request by escoand**
Add Dockerfile to get the external model fast up and running. One missing part is that the Nextcloud addon requires bzip2 and pdlib upon install and setup which is not the case on the official docker image `nextcloud:fpm-alpine`.

### CODE REVIEW

**Comment by matiasdelellis** [comment]
Hi @escoand 
Great.. This is a good service to implement in docker... 
Can you add some documentation about it?

**Comment by escoand** [comment]
I've added some instruction words.

I would like to request some more functionality:
- external clustering, so the Nextcloud addon could be run on any tiny sized device
- parallel HTTP calls, as currently the python dlib seems to use only one cpu

**Comment by afics** [comment]
> parallel HTTP calls, as currently the python dlib seems to use only one cpu
This would be great!

**Comment by matiasdelellis** [comment]
Wow, long time since you did that.. Sorry.. 😞 

well,  I'm going to merge it, and I think from here (Also with #2) we can do more interesting things.

>    external clustering, so the Nextcloud addon could be run on any tiny sized device
>    parallel HTTP calls, as currently the python dlib seems to use only one cpu

About this, it is unlikely that we will do something similar.. still need to improve other issues in the current architecture before attempting these changes. Sorry, but is always in consideration. 😉

**Pull request merged**
